---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  organisation-scp-pipeline Cloudformation
Parameters:
  Environment:
    Type: String
  OrganisationIDs:
    Type: CommaDelimitedList
    Description: List of OUs
  ExtraWhitelist:
    Type: String
    Description: Extra whitelist Services, have to start with ",", e.g ",bedrock:*"
    Default: ""
Resources:
  Common:
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: !Sub ${Environment}-common-whitelist
      TargetIds: !Ref OrganisationIDs
      Content:
        Version: '2012-10-17'
        Statement:
        - Sid: ServiceWhiteList
          Effect: Deny
          Resource: "*"
          NotAction: !Split
            - ","
            - !Sub 
              - "${existingWhitelistToString}${ExtraWhitelist}"
              - existingWhitelistToString: !Join
                - ","
                - - a4b:*
                  - access-analyzer:*
                  - account:*
                  - acm-pca:*
                  - acm:*
                  - amplify:*
                  - amplifybackend:*
                  - amplifyuibuilder:*
                  - apigateway:*
                  - appconfig:*
                  - applicationinsights:*
                  - apprunner:*
                  - appstream:*
                  - appsync:*
                  - aps:*
                  - artifact:*
                  - athena:*
                  - application-autoscaling:*
                  - autoscaling-plans:*
                  - autoscaling:*
                  - aws-marketplace-management:*
                  - aws-marketplace:*
                  - aws-portal:*
                  - awsconnector:*
                  - backup-gateway:*
                  - backup-storage:*
                  - backup:*
                  - batch:*
                  - billing:*
                  - billingconductor:*
                  - budgets:*
                  - ce:*
                  - chatbot:*
                  - cloud9:*
                  - clouddirectory:*
                  - cloudformation:*
                  - cloudfront:*
                  - cloudhsm:*
                  - cloudtrail:*
                  - cloudwatch:*
                  - codeartifact:*
                  - codebuild:*
                  - codecommit:*
                  - codedeploy-commands-secure:*
                  - codedeploy:*
                  - codepipeline:*
                  - codestar-connections:*
                  - codestar-notifications:*
                  - codestar:*
                  - cognito-identity:*
                  - cognito-idp:*
                  - cognito-sync:*
                  - comprehend:*
                  - compute-optimizer:*
                  - config:*
                  - connect:*
                  - consolidatedbilling:*
                  - controltower:*
                  - cur:*
                  - datapipeline:*
                  - datasync:*
                  - dax:*
                  - detective:*
                  - directconnect:*
                  - dlm:*
                  - dms:*
                  - docdb-elastic:*
                  - ds:*
                  - dynamodb:*
                  - ebs:*
                  - ec2-instance-connect:*
                  - ec2:*
                  - ec2messages:*
                  - ecr-public:*
                  - ecr:*
                  - ecs:*
                  - eks:*
                  - elasticache:*
                  - elasticbeanstalk:*
                  - elasticfilesystem:*
                  - elasticloadbalancing:*
                  - elasticmapreduce:*
                  - emr-containers:*
                  - es:*
                  - events:*
                  - evidently:*
                  - execute-api:*
                  - firehose:*
                  - fms:*
                  - freetier:*
                  - fsx:*
                  - geo:*
                  - glacier:*
                  - globalaccelerator:*
                  - glue:*
                  - grafana:*
                  - guardduty:*
                  - health:*
                  - healthlake:*
                  - iam:*
                  - identitystore:*
                  - imagebuilder:*
                  - importexport:*
                  - inspector2:*
                  - inspector:*
                  - invoicing:*
                  - kafka-cluster:*
                  - kafka:*
                  - kafkaconnect:*
                  - kinesis:*
                  - kinesisanalytics:*
                  - kinesisvideo:*
                  - kms:*
                  - lakeformation:*
                  - lambda:*
                  - launchwizard:*
                  - lex:*
                  - license-manager:*
                  - lightsail:*
                  - logs:*
                  - machinelearning:*
                  - macie2:*
                  - macie:*
                  - memorydb:*
                  - mgh:*
                  - mgn:*
                  - migrationhub-strategy:*
                  - mobileanalytics:*
                  - mq:*
                  - neptune-db:*
                  - network-firewall:*
                  - networkmanager:*
                  - opsworks-cm:*
                  - opsworks:*
                  - organizations:*
                  - payments:*
                  - pi:*
                  - pipes:*
                  - pricing:*
                  - profile:*
                  - purchase-orders:*
                  - quicksight:*
                  - ram:*
                  - rds-data:*
                  - rds-db:*
                  - rds:*
                  - redshift-data:*
                  - redshift:*
                  - refactor-spaces:*
                  - rekognition:*
                  - resiliencehub:*
                  - resource-explorer:*
                  - resource-groups:*
                  - route53-recovery-cluster:*
                  - route53-recovery-control-config:*
                  - route53-recovery-readiness:*
                  - route53:*
                  - route53domains:*
                  - route53resolver:*
                  - rum:*
                  - s3-object-lambda:*
                  - s3-outposts:*
                  - s3:*
                  - sagemaker:*
                  - savingsplans:*
                  - scheduler:*
                  - schemas:*
                  - sdb:*
                  - secretsmanager:*
                  - securityhub:*
                  - serverlessrepo:*
                  - servicecatalog:*
                  - serviceextract:*
                  - servicequotas:*
                  - ses:*
                  - shield:*
                  - sms:*
                  - snow-device-management:*
                  - snowball:*
                  - sns:*
                  - sqlworkbench:*
                  - sqs:*
                  - ssm-contacts:*
                  - ssm-incidents:*
                  - ssm:*
                  - ssmmessages:*
                  - sso-directory:*
                  - sso:*
                  - states:*
                  - storagegateway:*
                  - sts:*
                  - support:*
                  - sustainability:*
                  - synthetics:*
                  - tag:*
                  - tax:*
                  - textract:*
                  - timestream:*
                  - tiros:*
                  - transcribe:*
                  - transfer:*
                  - translate:*
                  - trustedadvisor:*
                  - waf-regional:*
                  - waf:*
                  - wafv2:*
                  - wellarchitected:*
                  - workspaces:*
                  - xray:*
